### ISSUE TITLE
[BUG] Unable to download files on Laravel Vapor

### ISSUE THREAD

**Issue by mforcer** [Maatwebsite/Laravel-Nova-Excel#119]
* [ x ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [ x ] Checked that your issue isn't already filed.
* [ x ] Checked if no PR was submitted that fixes this problem.

* PHP version: 8.0
* Laravel version: 8
* Nova version: 3.26.1
* Package version: 1.2.5

### Description

When attempting to export the data I get an error "Download failed - server problem" in the browser download list.

I've tested in multiple environments and it only occurs on Laravel Vapor.

I suspect this is due to Vapor being serverless and there's no real filesystem to store the output.

The URL it attempted to download from is:

https://mydomain.com/nova-vendor/maatwebsite/laravel-nova-excel/download?expires=1626191903&filename=orders.xlsx&path=eyJpdiI6IlhyQ1NmY3F2NTlpOTNUWERWblpQR0E9PSIsInZhbHVlIjoiZU1xVTJxWWVpWW53cTNDNXVUZUdnNzVnMVFyV2d0WW85M0xVNWtHRFNyZW5XdXR4UWh1NnJpUEp6OFBRbDgzUmw3eFZxVEQ5RE1ORmJyMDVhNDZJeFFhREJTdVFwcW41a2pRZDh0ZGI5eGlkRUYycjcwNHN0eUp5b0UxZkdQQ0wxdUFsV3plVWNkaWVqcXd6b0tDSmtRPT0iLCJtYWMiOiJiYTU5ZmM3ZjFmNmNlYmNlODMzOTJkN2Q5Y2VlMGM3YzI3ZWU2MWUxOWM5ZjRmN2JlNTdjY2M5NTc4Yjg3ZjljIn0%3D&signature=774eb749087101405882015284be304804d79bcd9f449b074c775991162602cd

The issue can be reproduced by attempting to download an Excel file using Nova actions when the application is sitting on Laravel Vapor.

I'd expect a working Excel file to be downloaded.

No file is downloaded, an error is presented.

**Comment by patrickbrouwers** [comment]
I'm not a Vapor user, so can't be of help. I know Laravel Excel itself works with Vapor, so no idea why it wouldn't work with. Afraid you'll have to debug this yourself and provide a PR

**Comment by mforcer** [comment]
> I'm not a Vapor user, so can't be of help. I know Laravel Excel itself works with Vapor, so no idea why it wouldn't work with. Afraid you'll have to debug this yourself and provide a PR

Thanks for responding. I did see some posts in the Laravel Excel repository and some changes were made to get around 'multi server' setup issues and Vapor was mentioned as well. Sadly I couldn't translate the 'fixes' over to Nova.

I believe a solution would be to use something like download streaming which avoids writing to disk. Could something like this be integrated into Laravel Excel? If so, I'd be happy to take a look.

Hopefully someone using Vapor can chime in :)

**Comment by juliusvdijk** [comment]
We are running into this issue without Laravel Vapor, instead Nova is running on multiple webservers behind a load balancer.

Excel::download will create a local file because it assumes that the response will be served to the user in the same request.
(Excel::download -> Excel::export -> Writer::export -> TemporaryFileFactory::makeLocal). 
While using Laravel Nova this assumption does not hold. The action handler creates the file but returns a signed url which is not guaranteed to run on the same server.

A possible solution is to use Excel::store instead of Excel::download in the DownloadExcel action.
The Laravel Excel configuration could be used to determine which disk should be used for Excel::store (`excel.temporary_files.remote_disk`, `excel.temporary_files.remote_prefix`).

@patrickbrouwers Let me know if you agree with this solution.

**Comment by patrickbrouwers** [comment]
@mforcer can you test the new release on your Vapor app? You'll have to use the remote_disk option as @juliusvdijk explained in his comment.
