### ISSUE TITLE
No response from DownloadExcel

### ISSUE THREAD

**Issue by ardyn** [Maatwebsite/Laravel-Nova-Excel#13]
Installed correctly, php7.2, laravel 5.6.38, orion 1.0.13.
added to actions array on a simple model with just one string field and id field
select all models on index view, run download excel action. request is sent, query is executed, but no response is received and no success message returned. nothing in error logs.

haven't dug very deep to diagnose. does anyone one else have issues?

**Comment by ardyn** [comment]
Okay, apparently auto discovery wasn't enabled and a 404 was returned when running the action, but we fixed that now have json response: 
```
{"download":"http:\/\/localhost\/nova-vendor\/maatwebsite\/laravel-nova-excel\/download?path=%2Ftmp%2Flaravel-excel-IL8mqQ53nRzHjdki&filename=customers.xlsx","name":"customers.xlsx"}
```

but no prompt to download the file.

**Comment by BengtHagemeister** [comment]
I have the same problem in Firefox (Firefox Quantum, 62.0 (64-Bit), macOS High Sierra). 
I get the same behaviour as @ardyn with a json response without a download prompt.

**Chrome and Safari are both working.**

**Comment by patrickbrouwers** [comment]
That’s a known Nova bug with firefox. (See their issue tracker) Nothing we can do about that here.

**Comment by patrickbrouwers** [comment]
https://github.com/laravel/nova-issues/issues/276

**Comment by nCuXaP** [comment]
Hello @patrickbrouwers. I use your packages for laravel excel and nova excel and they are wonderfull - thank you for them! I reacently started to get this error while using laravel excel resource export. I implemented it 2/3 months ago and it was working perfectly. This week I started getting this error "Invalid argument supplied to foreach". Nothing in the code has changed and also reverted the packages(Laravel excel), because I saw that there was a new version downloaded, but the same error keeps showing.

**Comment by GlennM** [comment]
> Nothing in the code has changed and also reverted the packages(Laravel excel), because I saw that there was a new version downloaded, but the same error keeps showing.

You mention there are no code changes, but are there no changes on the hosting level as well? E.g. other PHP version or different settings for error reporting?

**Comment by dillingham** [comment]
Ps your profile photos look identical at that size :)
