### ISSUE TITLE
How to get collection of models

### ISSUE THREAD

**Issue by JapSeyz** [Maatwebsite/Laravel-Nova-Excel#17]
Hey.

Is it possible to, in your own custom Action, get the models from the selected overview?

The Action documentation dictates that you can typehint it, but that's not possible because it would violate the DownloadExcel contract.

You can see the section of the docs here: https://nova.laravel.com/docs/1.0/actions/defining-actions.html#action-responses

I'd like to create a sheet per. model, and just use the first-sheet as a summary of the models. 
How would I go about that?

**Comment by patrickbrouwers** [comment]
We don't pass the models to the handle method as that impeeds performance. We pass the query on to Laravel Excel so that library can handle it in a more performant way.

If you want to do something completely different, can you execute the query like so:

```
/**
     * @param ExportActionRequest $request
     * @param Action              $exportable
     *
     * @return array
     */
    public function handle(ExportActionRequest $request, Action $exportable): array
    {
        $models = $exportable->query()->get();
    }
```

You most likely will have to create an Export class with the `WithMultipleSheets` concern. Please refer to the Laravel Excel docs for this: https://laravel-excel.maatwebsite.nl/3.0/exports/multiple-sheets.html#multiple-sheets

(Do note that you will loose all conviences that this package offers, you'll probably be better of creating an own action and using Laravel Excel library directly. )

**Comment by JapSeyz** [comment]
@patrickbrouwers Ah thanks.
Wonderful job with the package, thank you so much for your hard work!
