### ISSUE TITLE
[BUG] No longer works with the latest version of Laravel Nova (4.32.9)

### ISSUE THREAD

**Issue by Flavien-Panunzio** [Maatwebsite/Laravel-Nova-Excel#171]
* PHP version: 8.1.9
* Laravel version: 9.52.16
* Nova version: 4.32.9
* Package version: 1.3.6

### Description

Since I updated my version of Nova to version 4.32.9 (Silver Surfer), Excel data export no longer works at all. No error log and the success message is displayed correctly in Laravel Nova. So I tried to go down the version little by little in order to find when it no longer works, so I arrived at version 4.32.6 of Laravel Nova to make the plugin work again. From version 4.32.7, the plugin no longer works.

### Steps to Reproduce

Simply update nova to the latest version

**Expected behavior:**

Make an Excel data export

**Actual behavior:** 

Nothing. Just a confirmation from Laravel Nova, but no errors logs.

**Comment by balda38** [comment]
This is probably an issue with Nova itself. I found these issues in the nova-issues repo:

- https://github.com/laravel/nova-issues/issues/6098
- https://github.com/laravel/nova-issues/issues/6100

Btw, `Action::download()` is marked deprecated in favor of `Action::downloadUrl()` since Nova `4.24.0`! But the Nova documentation tells us to use `Action::download()` anyway https://nova.laravel.com/docs/actions/defining-actions.html#download-responses 🙃  But `Action::downloadUrl()` doesn't actually work for me as well

There is a temporary solution for this problem that one guy provided in one of the issues above. But i believe it's not suitable for `laravel-nova-excel` as third-party package. So, i'd prefer to use `4.32.6` for now as more stable version (@Flavien-Panunzio thanks for finding that version)

**Comment by Flavien-Panunzio** [comment]
This issue will be corrected during the next release of Nova, thank you !
[https://github.com/laravel/nova-issues/issues/6100#issuecomment-1852625576](https://github.com/laravel/nova-issues/issues/6100#issuecomment-1852625576)

**Comment by Flavien-Panunzio** [comment]
The release has just been published: https://nova.laravel.com/releases/4.32.10
